Registration
PayamZandiyeh/StereoFlouroscopyRegistration pull request #2
Opened 2018-01-22 17:09 UTC by PayamZandiyeh

I have made the necessary subfolders for different contributors to work on. Will it be possible to merge it to master if that's OK.

2018-01-22 18:04 UTC, Besler commented
FYI future commits should stick to the software guidelines in the README.md file.

**Software Guidelines**
We are going to follow the ITK Style for software development. Those rules roughly manifest themselves as such:

Do not push to master

- All work is done on a seperate branch: git checkout -b my-topic
- Merge on GitHub after at least one review
    - Follow standard prefixes for commits:
    - BUG: Fix for runtime crash or incorrect result
    - COMP: Compiler error or warning fix
    - DOC: Documentation change
    - ENH: New functionality
    - PERF: Performance improvement
    - STYLE: No logic impact (indentation, comments)
    - WIP: Work In Progress not ready for merge

2018-01-22 18:04 UTC, Besler commented
Also FYI you can request a review in the top right. Put my name in and I'll get a message!

2018-01-22 18:19 UTC, Besler requested changes
It's looking good! I can't make the comments on binary files, but could you do the following?

Remove all mhd/mha/pdf files? And remove them from history as well. See https://wikileaks.org/ciav7p1/cms/page_41123851.html for how to remove files from history. Note: you're rewriting history. Becareful with that power.

Typically, you don't version these files. You store them somewhere else and download them when you need them. And I don't think they're our files.

2018-01-22 18:19 UTC, Besler commented on Registration/3D2DRegistration/PythonImplementation/README.md
> +# StereoFlouroscopyRegistration
README should be specific to this directory. You shouldn't copy the old README

2018-01-22 18:19 UTC, Besler commented on Registration/MRI2PseudoCT/README.md
> +# StereoFlouroscopyRegistration
See previous README comments

2018-01-22 18:19 UTC, Besler commented on Registration/Segmentation/README.md
> +# StereoFlouroscopyRegistration
See previous README comments

2018-01-22 18:19 UTC, Besler commented on Registration/3D2DRegistration/PythonImplementation/SourceCode/ScrapProject.py
> +#%%
Could this be deleted?

2018-01-23 01:50 UTC, PayamZandiyeh commented
Hello Bryce, 
I have removed the files. 
I couldn’t access the git clone ssh://git@stash.devlan.net:7999/~User #524297/git-prune-files.git
It says 

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I will try again to “rewrite the history”. 
Thanks, 
Payam 

> On Jan 22, 2018, at 12:19 PM, Bryce Besler <notifications@github.com> wrote:
> 
> @Besler requested changes on this pull request.
> 
> It's looking good! I can't make the comments on binary files, but could you do the following?
> 
> Remove all mhd/mha/pdf files? And remove them from history as well. See https://wikileaks.org/ciav7p1/cms/page_41123851.html <https://wikileaks.org/ciav7p1/cms/page_41123851.html> for how to remove files from history. Note: you're rewriting history. Becareful with that power.
> 
> Typically, you don't version these files. You store them somewhere else and download them when you need them. And I don't think they're our files.
> 
> In Registration/3D2DRegistration/PythonImplementation/README.md <https://github.com/PayamZandiyeh/StereoFlouroscopyRegistration/pull/2#discussion_r163021505>:
> 
> > @@ -0,0 +1,29 @@
> +# StereoFlouroscopyRegistration
> README should be specific to this directory. You shouldn't copy the old README
> 
> In Registration/MRI2PseudoCT/README.md <https://github.com/PayamZandiyeh/StereoFlouroscopyRegistration/pull/2#discussion_r163021816>:
> 
> > @@ -0,0 +1,29 @@
> +# StereoFlouroscopyRegistration
> See previous README comments
> 
> In Registration/Segmentation/README.md <https://github.com/PayamZandiyeh/StereoFlouroscopyRegistration/pull/2#discussion_r163021884>:
> 
> > @@ -0,0 +1,29 @@
> +# StereoFlouroscopyRegistration
> See previous README comments
> 
> In Registration/3D2DRegistration/PythonImplementation/SourceCode/ScrapProject.py <https://github.com/PayamZandiyeh/StereoFlouroscopyRegistration/pull/2#discussion_r163022006>:
> 
> > @@ -0,0 +1 @@
> +#%%
> Could this be deleted?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/PayamZandiyeh/StereoFlouroscopyRegistration/pull/2#pullrequestreview-90571470>, or mute the thread <https://github.com/notifications/unsubscribe-auth/Ache7dHWX1cXzoL304jW_Xdfx78xC90uks5tNNFAgaJpZM4RoUAk>.
>

2018-01-23 01:51 UTC, Besler commented
Oh sorry! That was an example of how to clean up the git repo.

This looks great though! Thank you for removing the MHD data. Later tonight I'll commit my visualization code.

2018-01-23 01:51 UTC, Besler approved these changes

2018-01-23 01:52 UTC, Besler commented
Since you created the PR, you merge it into master. You get that sweet, sweet satisfaction!

I would recommend deleting the remote branch after. GitHub will just have a click button thing. 'Delete branch?'

2018-01-23 01:57 UTC, merged

2018-01-23 02:05 UTC, PayamZandiyeh commented
I have done as suggested. 
Thanks man! 
Cheers, 
Payam 

> On Jan 22, 2018, at 7:52 PM, Bryce Besler <notifications@github.com> wrote:
> 
> Since you created the PR, you merge it into master. You get that sweet, sweet satisfaction!
> 
> I would recommend deleting the remote branch after. GitHub will just have a click button thing. 'Delete branch?'
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/PayamZandiyeh/StereoFlouroscopyRegistration/pull/2#issuecomment-359643563>, or mute the thread <https://github.com/notifications/unsubscribe-auth/Ache7bFs5UTqpfbDgYh5iQLZiQN2woWwks5tNTtqgaJpZM4RoUAk>.
>